### ISSUE TITLE
Where is dico.txt from?

### ISSUE THREAD

**Issue by jpmckinney** [gaultier/CaesarDecryption#1]
I'm looking for a French word list and dico.txt looks pretty complete. What's its source?

**Comment by gaultier** [comment]
I think I got it from here: http://openclassrooms.com/uploads/fr/ftp/mateo21/pendu_siteduzero.zip
The archive is a totally different project but they also use this dictionary.

**Comment by jpmckinney** [comment]
Thanks! I figured out that it eventually ties back to the [GUTenberg](https://www.gutenberg.eu.org/) group, where Christophe Pythoud created a dictionary for ispell http://www.pallier.org/ressources/dicofr/dicofr.html
